// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddConfig(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function GetDefaultTemplate():Promise<string>;

export function GetFolderNames():Promise<Array<string>>;

export function GetMetadata():Promise<main.MetadataDTO>;

export function GetTunnelInfos():Promise<Array<main.TunnelInfoDTO>>;

export function ImportFiles():Promise<Array<string>>;

export function ImportFilesToFolder(arg1:string):Promise<Array<string>>;

export function ImportFolder():Promise<Array<string>>;

export function ImportFolderToFolder(arg1:string):Promise<Array<string>>;

export function MoveToFolder(arg1:string,arg2:string):Promise<void>;

export function RandomTunnelInFolder(arg1:string):Promise<string>;

export function ReadConfig(arg1:string):Promise<main.ConfigDTO>;

export function RenameTunnel(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetOnConfigChange(arg1:any):Promise<void>;
