// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfig(arg1, arg2) {
  return window['go']['main']['ConfigService']['AddConfig'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['main']['ConfigService']['CreateFolder'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['ConfigService']['DeleteFolder'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['ConfigService']['DeleteTunnel'](arg1);
}

export function GetDefaultTemplate() {
  return window['go']['main']['ConfigService']['GetDefaultTemplate']();
}

export function GetFolderNames() {
  return window['go']['main']['ConfigService']['GetFolderNames']();
}

export function GetMetadata() {
  return window['go']['main']['ConfigService']['GetMetadata']();
}

export function GetTunnelInfos() {
  return window['go']['main']['ConfigService']['GetTunnelInfos']();
}

export function ImportFiles() {
  return window['go']['main']['ConfigService']['ImportFiles']();
}

export function ImportFilesToFolder(arg1) {
  return window['go']['main']['ConfigService']['ImportFilesToFolder'](arg1);
}

export function ImportFolder() {
  return window['go']['main']['ConfigService']['ImportFolder']();
}

export function ImportFolderToFolder(arg1) {
  return window['go']['main']['ConfigService']['ImportFolderToFolder'](arg1);
}

export function MoveToFolder(arg1, arg2) {
  return window['go']['main']['ConfigService']['MoveToFolder'](arg1, arg2);
}

export function RandomTunnelInFolder(arg1) {
  return window['go']['main']['ConfigService']['RandomTunnelInFolder'](arg1);
}

export function ReadConfig(arg1) {
  return window['go']['main']['ConfigService']['ReadConfig'](arg1);
}

export function RenameTunnel(arg1, arg2) {
  return window['go']['main']['ConfigService']['RenameTunnel'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['ConfigService']['SaveConfig'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['ConfigService']['SetContext'](arg1);
}

export function SetOnConfigChange(arg1) {
  return window['go']['main']['ConfigService']['SetOnConfigChange'](arg1);
}
