// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs() {
  return window['go']['main']['LogService']['GetLogs']();
}

export function SetContext(arg1) {
  return window['go']['main']['LogService']['SetContext'](arg1);
}
