// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['TunnelService']['Connect'](arg1);
}

export function ConnectRandom(arg1) {
  return window['go']['main']['TunnelService']['ConnectRandom'](arg1);
}

export function Disconnect() {
  return window['go']['main']['TunnelService']['Disconnect']();
}

export function EmitStateChanged() {
  return window['go']['main']['TunnelService']['EmitStateChanged']();
}

export function GetStatus() {
  return window['go']['main']['TunnelService']['GetStatus']();
}

export function RefreshStatus() {
  return window['go']['main']['TunnelService']['RefreshStatus']();
}

export function SetContext(arg1) {
  return window['go']['main']['TunnelService']['SetContext'](arg1);
}
