// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function Connect(arg1:string):Promise<void>;

export function ConnectRandom(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function EmitStateChanged():Promise<void>;

export function GetStatus():Promise<main.StatusInfo>;

export function RefreshStatus():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
